# Generated by Django 3.1 on 2020-12-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20201219_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='precio_unitario',
            new_name='precio',
        ),
    ]
