# Generated by Django 3.1 on 2020-12-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20201219_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='precio_unitario',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
    ]
