# Generated by Django 3.1 on 2020-12-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20201219_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/articulos/'),
        ),
    ]
